apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-cluster
  region: eu-central-1

nodeGroups:
  - name: ng1-public
    instanceType: r5.large
    instanceName: custom-node-name
    desiredCapacity: 4
    minSize: 1                      
    maxSize: 1                      
    ssh:
      allow: true
      publicKeyPath: /Users/itziksavaia/.ssh/id_rsa.pub
  - name: ng2-private
    instanceType: r5.large
    desiredCapacity: 10
    minSize: 1             
    maxSize: 1             
